name: Build-Deploy-WebApp
on: [push]
env: # Modify values with your resources
  AZURE_WEBAPP_NAME: loadtestingweb
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  LOAD_TEST_RESOURCE_GROUP: 'LoadTestingSample'
  LOAD_TEST_RESOURCE: 'LoadTestingWebApp'
  DOTNET_VERSION: '7.0.x'
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}       
      - name: dotnet build and publish
        working-directory: LoadTestingWebApp
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WebApp'          
      - name: 'Azure deploy'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} 
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Add an publishing profile secret variable in your repository
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/WebApp'
  LoadTest:
    name: LoadTest
    needs: Build-and-Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main          
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Add an Azure Credential in GitHub Secrets to connect with Azure Load Testing
      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: 'LoadTestingConfig.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
          env: |
            [
              {
              "name": "webapp",
              "value": "${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
              }
            ]                
      - uses: actions/upload-artifact@v2
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/LoadTest